// Code generated by modelgen. DO NOT EDIT.
// 该模型由 users 表生成
package models

import (
	"time"

	"github.com/chslink/bizdb"
)

// Users 映射 users 表结构
// 索引信息：
// - PRIMARY (PRIMARY KEY): id
// - users_email_index (UNIQUE INDEX): email
type Users struct {
	Id       int64     `db:"id" json:"id"`               // Indexes: pk // 用户Id
	Name     string    `db:"name" json:"name"`           // 名字
	Email    string    `db:"email" json:"email"`         // Indexes: unique:users_email_index // 邮箱
	Age      int64     `db:"age" json:"age"`             // 年龄
	CreateAt time.Time `db:"create_at" json:"create_at"` // 创建时间
}

// TableName 返回表名
func (Users) TableName() string {
	return "users"
}

// Indexes 返回索引信息
func (m Users) Indexes() []bizdb.Index {
	return []bizdb.Index{
		{
			Name:   "PRIMARY",
			Fields: []string{"Id"},
			Unique: true,
			Type:   "BTREE",
		},
		{
			Name:   "users_email_index",
			Fields: []string{"Email"},
			Unique: true,
			Type:   "BTREE",
		},
	}
}

// Copy 返回一个深拷贝
func (m Users) Copy() *Users {
	return &Users{
		Id:       m.Id,
		Name:     m.Name,
		Email:    m.Email,
		Age:      m.Age,
		CreateAt: m.CreateAt,
	}
}
